-- Drop tables if exists (for resetting)
DROP TABLE IF EXISTS "CHITIETKIEMKHO" CASCADE;
DROP TABLE IF EXISTS "CHITIETPHIEUXUAT" CASCADE;
DROP TABLE IF EXISTS "CHITIETPHIEUNHAP" CASCADE;
DROP TABLE IF EXISTS "PHIEUKIEMKHO" CASCADE;
DROP TABLE IF EXISTS "PHIEUXUAT" CASCADE;
DROP TABLE IF EXISTS "PHIEUNHAP" CASCADE;
DROP TABLE IF EXISTS "CONGTHUC" CASCADE;
DROP TABLE IF EXISTS "NCC" CASCADE;
DROP TABLE IF EXISTS "NGUYENLIEU" CASCADE;
DROP TABLE IF EXISTS "THANHTOAN" CASCADE;
DROP TABLE IF EXISTS "CHITIETDONHANG" CASCADE;
DROP TABLE IF EXISTS "DONHANG" CASCADE;
DROP TABLE IF EXISTS "HOADON" CASCADE;
DROP TABLE IF EXISTS "CHITIETGIOHANG" CASCADE;
DROP TABLE IF EXISTS "GIOHANG" CASCADE;
DROP TABLE IF EXISTS "MON" CASCADE;
DROP TABLE IF EXISTS "MENU" CASCADE;
DROP TABLE IF EXISTS "BAN" CASCADE;
DROP TABLE IF EXISTS "TAIKHOAN" CASCADE;
DROP TABLE IF EXISTS "NHANVIEN" CASCADE;

-- 1. NHANVIEN
CREATE TABLE "NHANVIEN" (
    "MaNV" VARCHAR(20) PRIMARY KEY,
    "HoTen" VARCHAR(100) NOT NULL,
    "SoDienThoai" VARCHAR(15),
    "ViTri" VARCHAR(50),
    "TrangThai" VARCHAR(20) DEFAULT 'DangLam' -- DangLam, DaNghi
);

-- 2. TAIKHOAN
CREATE TABLE "TAIKHOAN" (
    "TenDangNhap" VARCHAR(50) PRIMARY KEY,
    "MatKhau" VARCHAR(255) NOT NULL,
    "QuyenHan" VARCHAR(50) NOT NULL, -- admin, thungan, phucvu, barista
    "MaNV" VARCHAR(20) UNIQUE REFERENCES "NHANVIEN"("MaNV") ON DELETE CASCADE
);

-- 3. MENU
CREATE TABLE "MENU" (
    "MaMenu" VARCHAR(20) PRIMARY KEY,
    "TenMenu" VARCHAR(100) NOT NULL,
    "MoTa" TEXT
);

-- 4. MON
CREATE TABLE "MON" (
    "MaMon" VARCHAR(20) PRIMARY KEY,
    "TenMon" VARCHAR(100) NOT NULL,
    "DonGia" DECIMAL(10, 0) NOT NULL,
    "HinhAnh" VARCHAR(255),
    "TrangThai" VARCHAR(20) DEFAULT 'ConMon', -- ConMon, HetMon
    "MaMenu" VARCHAR(20) REFERENCES "MENU"("MaMenu") ON DELETE SET NULL
);

-- 5. BAN
CREATE TABLE "BAN" (
    "MaBan" VARCHAR(20) PRIMARY KEY,
    "TenBan" VARCHAR(50) NOT NULL,
    "TrangThai" VARCHAR(20) DEFAULT 'Trong', -- Trong, DangCoKhach
    "QRCode" VARCHAR(255)
);

-- 6. GIOHANG
CREATE TABLE "GIOHANG" (
    "MaGio" VARCHAR(20) PRIMARY KEY,
    "ThoiGianTao" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "MaBan" VARCHAR(20) UNIQUE REFERENCES "BAN"("MaBan") ON DELETE CASCADE
);

-- 7. CHITIETGIOHANG
CREATE TABLE "CHITIETGIOHANG" (
    "MaGio" VARCHAR(20) REFERENCES "GIOHANG"("MaGio") ON DELETE CASCADE,
    "MaMon" VARCHAR(20) REFERENCES "MON"("MaMon") ON DELETE CASCADE,
    "SoLuong" INT NOT NULL DEFAULT 1,
    "GhiChu" VARCHAR(255),
    PRIMARY KEY ("MaGio", "MaMon")
);

-- 8. HOADON
CREATE TABLE "HOADON" (
    "MaHD" VARCHAR(20) PRIMARY KEY,
    "ThoiGianXuat" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TongTien" DECIMAL(12, 0) NOT NULL,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);

-- 9. DONHANG
CREATE TABLE "DONHANG" (
    "MaDH" VARCHAR(20) PRIMARY KEY,
    "ThoiGianDat" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TrangThaiOrder" VARCHAR(20) DEFAULT 'Cho', -- Cho, DangLam, HoanThanh, DaGiao
    "MaBan" VARCHAR(20) REFERENCES "BAN"("MaBan") ON DELETE SET NULL,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL,
    "MaHD" VARCHAR(20) REFERENCES "HOADON"("MaHD") ON DELETE SET NULL
);

-- 10. CHITIETDONHANG
CREATE TABLE "CHITIETDONHANG" (
    "MaDH" VARCHAR(20) REFERENCES "DONHANG"("MaDH") ON DELETE CASCADE,
    "MaMon" VARCHAR(20) REFERENCES "MON"("MaMon") ON DELETE CASCADE,
    "SoLuong" INT NOT NULL,
    "DonGia" DECIMAL(10, 0) NOT NULL,
    "GhiChu" VARCHAR(255),
    PRIMARY KEY ("MaDH", "MaMon")
);

-- 11. THANHTOAN
CREATE TABLE "THANHTOAN" (
    "MaThanhToan" VARCHAR(20) PRIMARY KEY,
    "ThoiGianThanhToan" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "SoTien" DECIMAL(12, 0) NOT NULL,
    "PhuongThuc" VARCHAR(20), -- TienMat, CK, Visa
    "MaHD" VARCHAR(20) UNIQUE REFERENCES "HOADON"("MaHD") ON DELETE CASCADE,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);

-- 12. NGUYENLIEU
CREATE TABLE "NGUYENLIEU" (
    "MaNL" VARCHAR(20) PRIMARY KEY,
    "TenNL" VARCHAR(100) NOT NULL,
    "DonViTinh" VARCHAR(20) NOT NULL,
    "SoLuongTon" DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK ("SoLuongTon" >= 0),
    "MucToiThieu" DECIMAL(10, 2) NOT NULL DEFAULT 0 CHECK ("MucToiThieu" >= 0)
);

-- 13. CONGTHUC
CREATE TABLE "CONGTHUC" (
    "MaMon" VARCHAR(20) REFERENCES "MON"("MaMon") ON DELETE CASCADE,
    "MaNL" VARCHAR(20) REFERENCES "NGUYENLIEU"("MaNL") ON DELETE CASCADE,
    "DinhLuong" DECIMAL(10, 2) NOT NULL CHECK ("DinhLuong" > 0),
    PRIMARY KEY ("MaMon", "MaNL")
);

-- 14. NCC
CREATE TABLE "NCC" (
    "MaNCC" VARCHAR(20) PRIMARY KEY,
    "TenNCC" VARCHAR(100) NOT NULL,
    "SoDienThoai" VARCHAR(15) NOT NULL,
    "DiaChi" TEXT
);

-- 15. PHIEUNHAP
CREATE TABLE "PHIEUNHAP" (
    "MaPN" VARCHAR(20) PRIMARY KEY,
    "NgayNhap" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TongTienNhap" DECIMAL(12, 0) NOT NULL DEFAULT 0 CHECK ("TongTienNhap" >= 0),
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL,
    "MaNCC" VARCHAR(20) REFERENCES "NCC"("MaNCC") ON DELETE SET NULL
);

-- 16. CHITIETPHIEUNHAP
CREATE TABLE "CHITIETPHIEUNHAP" (
    "MaPN" VARCHAR(20) REFERENCES "PHIEUNHAP"("MaPN") ON DELETE CASCADE,
    "MaNL" VARCHAR(20) REFERENCES "NGUYENLIEU"("MaNL") ON DELETE CASCADE,
    "SoLuong" DECIMAL(10, 2) NOT NULL CHECK ("SoLuong" > 0),
    "DonGiaNhap" DECIMAL(10, 0) NOT NULL CHECK ("DonGiaNhap" > 0),
    PRIMARY KEY ("MaPN", "MaNL")
);

-- 17. PHIEUXUAT
CREATE TABLE "PHIEUXUAT" (
    "MaPX" VARCHAR(20) PRIMARY KEY,
    "NgayXuat" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "LyDo" VARCHAR(50) NOT NULL, -- 'Xuat quay', 'Xuat huy'
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);

-- 18. CHITIETPHIEUXUAT
CREATE TABLE "CHITIETPHIEUXUAT" (
    "MaPX" VARCHAR(20) REFERENCES "PHIEUXUAT"("MaPX") ON DELETE CASCADE,
    "MaNL" VARCHAR(20) REFERENCES "NGUYENLIEU"("MaNL") ON DELETE CASCADE,
    "SoLuong" DECIMAL(10, 2) NOT NULL CHECK ("SoLuong" > 0),
    PRIMARY KEY ("MaPX", "MaNL")
);

-- 19. PHIEUKIEMKHO
CREATE TABLE "PHIEUKIEMKHO" (
    "MaPKK" VARCHAR(20) PRIMARY KEY,
    "NgayKiem" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TrangThai" VARCHAR(20) NOT NULL, -- 'Khop', 'Lech'
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);

-- 20. CHITIETKIEMKHO
CREATE TABLE "CHITIETKIEMKHO" (
    "MaPKK" VARCHAR(20) REFERENCES "PHIEUKIEMKHO"("MaPKK") ON DELETE CASCADE,
    "MaNL" VARCHAR(20) REFERENCES "NGUYENLIEU"("MaNL") ON DELETE CASCADE,
    "SLThucTe" DECIMAL(10, 2) NOT NULL CHECK ("SLThucTe" >= 0),
    "SLLyThuyet" DECIMAL(10, 2) NOT NULL CHECK ("SLLyThuyet" >= 0),
    "ChenhLech" DECIMAL(10, 2) NOT NULL,
    "GhiChu" TEXT,
    PRIMARY KEY ("MaPKK", "MaNL")
);
