-- Drop tables if exists (for resetting)
DROP TABLE IF EXISTS "THANHTOAN" CASCADE;
DROP TABLE IF EXISTS "CHITIETDONHANG" CASCADE;
DROP TABLE IF EXISTS "DONHANG" CASCADE;
DROP TABLE IF EXISTS "HOADON" CASCADE;
DROP TABLE IF EXISTS "CHITIETGIOHANG" CASCADE;
DROP TABLE IF EXISTS "GIOHANG" CASCADE;
DROP TABLE IF EXISTS "MON" CASCADE;
DROP TABLE IF EXISTS "MENU" CASCADE;
DROP TABLE IF EXISTS "BAN" CASCADE;
DROP TABLE IF EXISTS "TAIKHOAN" CASCADE;
DROP TABLE IF EXISTS "NHANVIEN" CASCADE;

-- 1. NHANVIEN
CREATE TABLE "NHANVIEN" (
    "MaNV" VARCHAR(20) PRIMARY KEY,
    "HoTen" VARCHAR(100) NOT NULL,
    "SoDienThoai" VARCHAR(15),
    "ViTri" VARCHAR(50),
    "TrangThai" VARCHAR(20) DEFAULT 'DangLam' -- DangLam, DaNghi
);

-- 2. TAIKHOAN
CREATE TABLE "TAIKHOAN" (
    "TenDangNhap" VARCHAR(50) PRIMARY KEY,
    "MatKhau" VARCHAR(255) NOT NULL,
    "QuyenHan" VARCHAR(50) NOT NULL, -- admin, thungan, phucvu, barista
    "MaNV" VARCHAR(20) UNIQUE REFERENCES "NHANVIEN"("MaNV") ON DELETE CASCADE
);

-- 3. MENU
CREATE TABLE "MENU" (
    "MaMenu" VARCHAR(20) PRIMARY KEY,
    "TenMenu" VARCHAR(100) NOT NULL,
    "MoTa" TEXT
);

-- 4. MON
CREATE TABLE "MON" (
    "MaMon" VARCHAR(20) PRIMARY KEY,
    "TenMon" VARCHAR(100) NOT NULL,
    "DonGia" DECIMAL(10, 0) NOT NULL,
    "HinhAnh" VARCHAR(255),
    "TrangThai" VARCHAR(20) DEFAULT 'ConMon', -- ConMon, HetMon
    "MaMenu" VARCHAR(20) REFERENCES "MENU"("MaMenu") ON DELETE SET NULL
);

-- 5. BAN
CREATE TABLE "BAN" (
    "MaBan" VARCHAR(20) PRIMARY KEY,
    "TenBan" VARCHAR(50) NOT NULL,
    "TrangThai" VARCHAR(20) DEFAULT 'Trong', -- Trong, DangCoKhach
    "QRCode" VARCHAR(255)
);

-- 6. GIOHANG
CREATE TABLE "GIOHANG" (
    "MaGio" VARCHAR(20) PRIMARY KEY,
    "ThoiGianTao" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "MaBan" VARCHAR(20) UNIQUE REFERENCES "BAN"("MaBan") ON DELETE CASCADE
);

-- 7. CHITIETGIOHANG
CREATE TABLE "CHITIETGIOHANG" (
    "MaGio" VARCHAR(20) REFERENCES "GIOHANG"("MaGio") ON DELETE CASCADE,
    "MaMon" VARCHAR(20) REFERENCES "MON"("MaMon") ON DELETE CASCADE,
    "SoLuong" INT NOT NULL DEFAULT 1,
    "GhiChu" VARCHAR(255),
    PRIMARY KEY ("MaGio", "MaMon")
);

-- 8. HOADON
CREATE TABLE "HOADON" (
    "MaHD" VARCHAR(20) PRIMARY KEY,
    "ThoiGianXuat" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TongTien" DECIMAL(12, 0) NOT NULL,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);

-- 9. DONHANG
CREATE TABLE "DONHANG" (
    "MaDH" VARCHAR(20) PRIMARY KEY,
    "ThoiGianDat" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "TrangThaiOrder" VARCHAR(20) DEFAULT 'Cho', -- Cho, DangLam, HoanThanh, DaGiao
    "MaBan" VARCHAR(20) REFERENCES "BAN"("MaBan") ON DELETE SET NULL,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL,
    "MaHD" VARCHAR(20) REFERENCES "HOADON"("MaHD") ON DELETE SET NULL
);

-- 10. CHITIETDONHANG
CREATE TABLE "CHITIETDONHANG" (
    "MaDH" VARCHAR(20) REFERENCES "DONHANG"("MaDH") ON DELETE CASCADE,
    "MaMon" VARCHAR(20) REFERENCES "MON"("MaMon") ON DELETE CASCADE,
    "SoLuong" INT NOT NULL,
    "DonGia" DECIMAL(10, 0) NOT NULL,
    "GhiChu" VARCHAR(255),
    PRIMARY KEY ("MaDH", "MaMon")
);

-- 11. THANHTOAN
CREATE TABLE "THANHTOAN" (
    "MaThanhToan" VARCHAR(20) PRIMARY KEY,
    "ThoiGianThanhToan" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "SoTien" DECIMAL(12, 0) NOT NULL,
    "PhuongThuc" VARCHAR(20), -- TienMat, CK, Visa
    "MaHD" VARCHAR(20) UNIQUE REFERENCES "HOADON"("MaHD") ON DELETE CASCADE,
    "MaNV" VARCHAR(20) REFERENCES "NHANVIEN"("MaNV") ON DELETE SET NULL
);
